pipeline:
  build:
    image: docker/compose:1.23.2
    commands:
      - cp .env-template .env
      - docker-compose down --rmi all -v
      - docker-compose build --no-cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  deploy:
    image: docker/compose:1.23.2
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.hw.yml up
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    detach: true

  test:
    image: docker/compose:1.23.2
    commands:
      - docker-compose run client ./start_test.bash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  cleanup:
    image: docker/compose:1.23.2
    commands:
      - docker-compose down
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock