kind: pipeline
name: default
steps:
  - name: build
    image: docker/compose:1.23.2
    commands:
      - cp .env-template .env
      - docker network prune -f || true
      - docker-compose down --rmi all -v || true
      - docker-compose build --no-cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: deploy
    image: docker/compose:1.23.2
    commands:
      - docker-compose -f docker-compose.yml -f docker-compose.hw.yml up
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - name: isgx
        path: /dev/isgx
    detach: true

  - name: test
    image: docker/compose:1.23.2
    commands:
      - docker-compose run client ./start_test.bash
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  - name: cleanup
    image: docker/compose:1.23.2
    commands:
      - docker-compose down
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  - name: isgx
    host:
      path: /dev/isgx