version: '3'

services:

  contract:
    build:
      context: enigma-contract
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: contract
    entrypoint:
      - /bin/bash
      - -c
      - ./launch_ganache.bash; bash
    environment:
      - SGX_MODE=${SGX_MODE}
    volumes:
      - "built_contracts:/root/enigma-contract/build/contracts"
      - "shared:/root/.enigma"

  p2p:
    build: 
      context: enigma-p2p
      args:
        - GIT_BRANCH_P2P=${GIT_BRANCH_P2P}
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: p2p
    entrypoint:
      - /bin/bash
      - -c
      - ./start_worker.bash; bash
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}
    volumes:
        - "built_contracts:/root/enigma-p2p/test/ethereum/scripts/build/contracts"

  client:
    build:
      context: enigma-contract
      args:
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: client
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}
      - NODES
      - SGX_MODE
    volumes:
      - "built_contracts:/root/enigma-contract/build/contracts"

  core:
    build:
      context: enigma-core
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    hostname: core
    networks:
      - net

  km:
    build:
      context: enigma-core
      dockerfile: Dockerfile.km
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    hostname: km
    networks:
      - net
    volumes:
      - "shared:/root/.enigma"

networks:
    net:

volumes:
  built_contracts:
  shared:
