version: '3'

services:

  contract:
    build:
      context: enigma-contract
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    ports:
      - "9545:9545"
    networks:
      - net
    hostname: contract
    entrypoint:
      - /bin/bash
      - -c
      - ./start_ganache.bash; bash 
    volumes:
      - "built_contracts:/root/enigma-contract/build/contracts"
      - "shared:/root/.enigma"

  # p2p-proxy:
  #   build: 
  #     context: enigma-p2p
  #     args:
  #       - GIT_BRANCH_P2P=${GIT_BRANCH_P2P}
  #   stdin_open: true
  #   tty: true
  #   ports:
  #       - "3346:3346"
  #       - "10300:10300"
  #   networks:
  #       - net
  #   hostname: p2p_proxy
  #   entrypoint:
  #       - /bin/bash
  #       - -c
  #       - cd enigma-p2p/src/cli && node cli_app.js -i B1 -b B1 -p B1 --core 127.0.0.1:1543 --proxy 3346 --random-db; bash
  #   volumes:
  #       - "/home/eng-user/enigma-p2p:/root/enigma-p2p"

  p2p:
    build: 
      context: enigma-p2p
      args:
        - GIT_BRANCH_P2P=${GIT_BRANCH_P2P}
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: p2p
    entrypoint:
      - /bin/bash
      - -c
      - ./start_worker.bash; bash
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}
    volumes:
        - "built_contracts:/root/enigma-p2p/test/ethereum/scripts/build/contracts"

  client:
    build:
      context: enigma-contract
      args:
        - GIT_BRANCH_CONTRACT=${GIT_BRANCH_CONTRACT}
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: client
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}
      - NODES
    volumes:
      - "built_contracts:/root/enigma-contract/build/contracts"

  core:
    build:
      context: enigma-core
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    hostname: core
    networks:
      - net

  principal:
    build:
      context: enigma-core
      dockerfile: Dockerfile.principal
      args:
        - SGX_MODE=${SGX_MODE}
        - GIT_BRANCH_CORE=${GIT_BRANCH_CORE}
    stdin_open: true
    tty: true
    ports:
      - "3040:3040"
    hostname: enigma_principal
    networks:
      - net
    volumes:
      - "shared:/root/.enigma"

networks:
    net:

volumes:
  built_contracts:
  shared:
