version: '3'

services:

  contract:
    image: enigmampc/enigma_contract:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.type == contract
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: contract
    entrypoint:
      - /bin/bash
      - -c
      - ./launch_ganache.bash; bash
    environment:
      - SGX_MODE=${SGX_MODE}

  p2p:
    image: enigmampc/enigma_p2p:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.type == worker
      mode: global
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: p2p
    entrypoint:
      - /bin/bash
      - -c
      - ./start_worker.bash; bash
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}

  client:
    image: enigmampc/enigma_contract:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.type == client
    stdin_open: true
    tty: true
    networks:
      - net
    hostname: client
    environment:
      - NETWORK=${COMPOSE_PROJECT_NAME}
      - NODES
      - SGX_MODE

  core:
    image: enigmampc/enigma_core_sw:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.type == worker
      mode: global
    stdin_open: true
    tty: true
    hostname: core
    networks:
      - net

  km:
    image: enigmampc/enigma_km_sw:${DOCKER_TAG}
    deploy:
      placement:
        constraints:
          - node.labels.type == km
    stdin_open: true
    tty: true
    hostname: km
    networks:
      - net

networks:
  net:

volumes:
  built_contracts:
  shared:
